fail_fast: true
repos:
- repo: https://github.com/gruntwork-io/pre-commit
  rev: 'v0.1.17'
  hooks:
    - id: terraform-fmt
    - id: terragrunt-hclfmt
    - id: terraform-validate
    - id: tflint
- repo: https://github.com/bridgecrewio/checkov.git
  rev: '2.0.1098' # change to tag or sha
  hooks:
    - id: checkov
- repo: https://github.com/terraform-docs/terraform-docs
  rev: "v0.16.0"
  hooks:
    - id: terraform-docs-go
      args: ["markdown", "table", "--output-file", "README.md", "./image-pull-secrets"]
