formatter: "markdown" # this is required

sort:
  enabled: true
  by: name

settings:
  anchor: false
  color: false
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: false
  read-comments: true
  required: true
  sensitive: true
  type: true
  providers: false
